// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBgtSiUX_vDMIL41OZidwoHS0i8uOENqys',
//     appId: '1:1050192638057:web:838cf72e60b50438e632f8',
//     messagingSenderId: '1050192638057',
//     projectId: 'finalnti',
//     authDomain: 'finalnti.firebaseapp.com',
//     storageBucket: 'finalnti.firebasestorage.app',
//     measurementId: 'G-BN2478TWPY',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBo3Xu9aiFT60SegACiK5eJh6vTrE-w55Q',
//     appId: '1:1050192638057:android:b4d98b27d25371dee632f8',
//     messagingSenderId: '1050192638057',
//     projectId: 'finalnti',
//     storageBucket: 'finalnti.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyC0zT4VLFDEf5zJwqOk6J9FystxZAk4oHU',
//     appId: '1:1050192638057:ios:9bd30f344204257be632f8',
//     messagingSenderId: '1050192638057',
//     projectId: 'finalnti',
//     storageBucket: 'finalnti.firebasestorage.app',
//     iosBundleId: 'com.example.eCommerce',
//   );
// }
